// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProcrastiInfrastructure;

#nullable disable

namespace ProcrastiInfrastructure.Migrations
{
    [DbContext(typeof(ProcrastiContext))]
    partial class ProcrastiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProcrastiDomain.Model.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("achievementid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<bool?>("Ishidden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("ishidden");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("achievements_pkey");

                    b.HasIndex(new[] { "Code" }, "achievements_code_key")
                        .IsUnique();

                    b.ToTable("achievements", (string)null);
                });

            modelBuilder.Entity("ProcrastiDomain.Model.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("activityid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Categoryid")
                        .HasColumnType("integer")
                        .HasColumnName("categoryid");

                    b.Property<bool>("Isverified")
                        .HasColumnType("boolean")
                        .HasColumnName("isverified");

                    b.Property<int?>("Mentionscount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("mentionscount");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("activities_pkey");

                    b.HasIndex("Categoryid");

                    b.ToTable("activities", (string)null);
                });

            modelBuilder.Entity("ProcrastiDomain.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("categoryid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("categories_pkey");

                    b.HasIndex(new[] { "Name" }, "categories_name_key")
                        .IsUnique();

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("ProcrastiDomain.Model.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("commentid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Authorid")
                        .HasColumnType("integer")
                        .HasColumnName("authorid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("Logid")
                        .HasColumnType("integer")
                        .HasColumnName("logid");

                    b.Property<int?>("Parentcommentid")
                        .HasColumnType("integer")
                        .HasColumnName("parentcommentid");

                    b.HasKey("Id")
                        .HasName("comments_pkey");

                    b.HasIndex("Authorid");

                    b.HasIndex("Logid");

                    b.HasIndex("Parentcommentid");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("ProcrastiDomain.Model.Globalstat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Lastupdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastupdated")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("Totallossamount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("totallossamount");

                    b.HasKey("Id")
                        .HasName("globalstats_pkey");

                    b.ToTable("globalstats", (string)null);
                });

            modelBuilder.Entity("ProcrastiDomain.Model.Like", b =>
                {
                    b.Property<int>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.Property<int>("Logid")
                        .HasColumnType("integer")
                        .HasColumnName("logid");

                    b.HasKey("Userid", "Logid");

                    b.HasIndex("Logid");

                    b.ToTable("likes", (string)null);
                });

            modelBuilder.Entity("ProcrastiDomain.Model.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("logid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Activityid")
                        .HasColumnType("integer")
                        .HasColumnName("activityid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("Isvisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isvisible");

                    b.Property<int?>("Likescount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("likescount");

                    b.Property<int>("Logtype")
                        .HasColumnType("log_type")
                        .HasColumnName("logtype");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<int?>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("logs_pkey");

                    b.HasIndex("Activityid");

                    b.HasIndex("Userid");

                    b.ToTable("logs", (string)null);
                });

            modelBuilder.Entity("ProcrastiDomain.Model.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("notificationid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("Isviewed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isviewed");

                    b.Property<string>("Link")
                        .HasColumnType("text")
                        .HasColumnName("link");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("notifications_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("ProcrastiDomain.Model.Title", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("titleid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<bool?>("Isunique")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isunique");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("titles_pkey");

                    b.HasIndex(new[] { "Code" }, "titles_code_key")
                        .IsUnique();

                    b.ToTable("titles", (string)null);
                });

            modelBuilder.Entity("ProcrastiDomain.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("email");

                    b.Property<bool?>("Isadmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isadmin");

                    b.Property<bool?>("Isbanned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isbanned");

                    b.Property<DateTime?>("Joineddate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("joineddate")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Passwordhash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passwordhash");

                    b.Property<string>("Profilepicture")
                        .HasColumnType("text")
                        .HasColumnName("profilepicture");

                    b.Property<int?>("Titleid")
                        .HasColumnType("integer")
                        .HasColumnName("titleid");

                    b.Property<int?>("Totalloss")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("totalloss");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex("Titleid");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ProcrastiDomain.Model.Userachievement", b =>
                {
                    b.Property<int>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.Property<int>("Achievementid")
                        .HasColumnType("integer")
                        .HasColumnName("achievementid");

                    b.Property<DateTime?>("Unlockedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("unlockedat")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Userid", "Achievementid")
                        .HasName("userachievements_pkey");

                    b.HasIndex("Achievementid");

                    b.ToTable("userachievements", (string)null);
                });

            modelBuilder.Entity("ProcrastiDomain.Model.Usertitle", b =>
                {
                    b.Property<int>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.Property<int>("Titleid")
                        .HasColumnType("integer")
                        .HasColumnName("titleid");

                    b.Property<DateTime?>("Unlockedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("unlockedat")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Userid", "Titleid")
                        .HasName("usertitles_pkey");

                    b.HasIndex("Titleid");

                    b.ToTable("usertitles", (string)null);
                });

            modelBuilder.Entity("ProcrastiDomain.Model.Activity", b =>
                {
                    b.HasOne("ProcrastiDomain.Model.Category", "Category")
                        .WithMany("Activities")
                        .HasForeignKey("Categoryid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_category");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ProcrastiDomain.Model.Comment", b =>
                {
                    b.HasOne("ProcrastiDomain.Model.User", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("Authorid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_author");

                    b.HasOne("ProcrastiDomain.Model.Log", "Log")
                        .WithMany("Comments")
                        .HasForeignKey("Logid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_log");

                    b.HasOne("ProcrastiDomain.Model.Comment", "Parentcomment")
                        .WithMany("InverseParentcomment")
                        .HasForeignKey("Parentcommentid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_parentcomment");

                    b.Navigation("Author");

                    b.Navigation("Log");

                    b.Navigation("Parentcomment");
                });

            modelBuilder.Entity("ProcrastiDomain.Model.Like", b =>
                {
                    b.HasOne("ProcrastiDomain.Model.Log", "Log")
                        .WithMany("Likes")
                        .HasForeignKey("Logid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcrastiDomain.Model.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Log");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProcrastiDomain.Model.Log", b =>
                {
                    b.HasOne("ProcrastiDomain.Model.Activity", "Activity")
                        .WithMany("Logs")
                        .HasForeignKey("Activityid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_activity");

                    b.HasOne("ProcrastiDomain.Model.User", "User")
                        .WithMany("LogsNavigation")
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_user");

                    b.Navigation("Activity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProcrastiDomain.Model.Notification", b =>
                {
                    b.HasOne("ProcrastiDomain.Model.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProcrastiDomain.Model.User", b =>
                {
                    b.HasOne("ProcrastiDomain.Model.Title", "Title")
                        .WithMany("Users")
                        .HasForeignKey("Titleid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_title");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("ProcrastiDomain.Model.Userachievement", b =>
                {
                    b.HasOne("ProcrastiDomain.Model.Achievement", "Achievement")
                        .WithMany("Userachievements")
                        .HasForeignKey("Achievementid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("userachievements_achievementid_fkey");

                    b.HasOne("ProcrastiDomain.Model.User", "User")
                        .WithMany("Userachievements")
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("userachievements_userid_fkey");

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProcrastiDomain.Model.Usertitle", b =>
                {
                    b.HasOne("ProcrastiDomain.Model.Title", "Title")
                        .WithMany("Usertitles")
                        .HasForeignKey("Titleid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("usertitles_titleid_fkey");

                    b.HasOne("ProcrastiDomain.Model.User", "User")
                        .WithMany("Usertitles")
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("usertitles_userid_fkey");

                    b.Navigation("Title");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProcrastiDomain.Model.Achievement", b =>
                {
                    b.Navigation("Userachievements");
                });

            modelBuilder.Entity("ProcrastiDomain.Model.Activity", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("ProcrastiDomain.Model.Category", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("ProcrastiDomain.Model.Comment", b =>
                {
                    b.Navigation("InverseParentcomment");
                });

            modelBuilder.Entity("ProcrastiDomain.Model.Log", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("ProcrastiDomain.Model.Title", b =>
                {
                    b.Navigation("Users");

                    b.Navigation("Usertitles");
                });

            modelBuilder.Entity("ProcrastiDomain.Model.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");

                    b.Navigation("LogsNavigation");

                    b.Navigation("Notifications");

                    b.Navigation("Userachievements");

                    b.Navigation("Usertitles");
                });
#pragma warning restore 612, 618
        }
    }
}
